server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${postgres.host}:5432/app
    username: app
    password: app
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl