version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  configserver:
    build: configserver/.
    image: spring-cloud-postgres-demo/cloud-configserver:1
    ports:
      - "8888:8888"
  eureka:
    build: eureka/.
    image: spring-cloud-postgres-demo/cloud-eureka:1
    ports:
      - "8761:8761"
    environment:
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - configserver
  edgeservice:
    build: edgeservice/.
    image: spring-cloud-postgres-demo/cloud-edgeservice:1
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka
      - ZIPKIN_HOST=zipkin
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - eureka
  userservice:
    build: userservice/.
    image: spring-cloud-postgres-demo/hellodocker:1
    environment:
      - EUREKA_HOST=eureka
      - CONFIGSERVER_HOST=configserver
    depends_on:
      - eureka
