version: '3'

services:
  eureka:
    build: .
    image: spring-cloud-postgres-demo/cloud-eureka:1
    ports:
      - "8761:8761"
    environment:
      - CONFIGSERVER_HOST=configserver

networks:
  default:
    external:
      name: spring-cloud-postgres-demo_default